services:
    airflow:
        image: apache/airflow:3.2.0
        container_name: airflow
        restart: always
        environment:
            - AIRFLOW__CORE__EXECUTOR=LocalExecutor
            - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@db-airflow/airflow
            - AIRFLOW__CORE__FERNET_KEY=your_fernet_key
            - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=True
            - AIRFLOW__CORE__LOAD_EXAMPLES=False
            - AIRFLOW__CORE__DAGS_FOLDER=/opt/airflow/task/dags
            - PYTHONPATH=/opt/airflow
        volumes:
            - ./task:/opt/airflow/task
        ports:
            - "8080:8080"
        command: bash -c "airflow standalone"
        depends_on:
            db-airflow:
                condition: service_healthy

    db-airflow:
        image: postgres:18-alpine3.23
        container_name: db-airflow
        restart: always
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        volumes:
            - airflow-postgres_data:/var/lib/postgresql/data-airflow
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U airflow -d airflow -h localhost"]
            interval: 5m
            timeout: 30s
            retries: 3
            start_period: 10s

    duck-ui:
        image: ghcr.io/caioricciuti/duck-ui:latest
        container_name: duck-ui
        ports:
            - "5522:5522"
        environment:
            - DUCK_UI_ALLOW_UNSIGNED_EXTENSIONS=true

    minio:
        image: minio/minio
        container_name: minio
        ports:
            - "9000:9000"
            - "9001:9001"
        environment:
            - MINIO_ROOT_USER=minio
            - MINIO_ROOT_PASSWORD=miniopass
            - MINIO_STORAGE_USE_HTTPS=False
        command: server /data --console-address ":9001"
        volumes:
            - datalake:/data
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
            interval: 1m30s
            timeout: 30s
            retries: 5
            start_period: 30s
        restart: always

    superset:
        image: apache/superset:latest
        container_name: superset_app
        restart: unless-stopped
        depends_on:
            db-airflow:
                condition: service_healthy
            superset_redis:
                condition: service_started
        environment:
            SUPERSET_SECRET_KEY: "super-secret-key-change-me"
            DATABASE_DB: airflow
            DATABASE_HOST: db-airflow
            DATABASE_PASSWORD: airflow
            DATABASE_USER: airflow
            DATABASE_PORT: 5432
            REDIS_HOST: superset_redis
            REDIS_PORT: 6379
            SUPERSET_LOAD_EXAMPLES: "no"
        ports:
            - "8088:8088"
        volumes:
            - superset_home:/app/superset_home
        command: >
            /bin/bash -c "
            superset db upgrade &&
            superset fab create-admin \
                --username admin \
                --firstname Superset \
                --lastname Admin \
                --email admin@superset.com \
                --password admin &&
            superset init &&
            superset run -h 0.0.0.0 -p 8088
            "


    superset_redis:
        image: redis:7
        container_name: superset_redis
        restart: unless-stopped
        volumes:
        - superset_redis_data:/data




volumes:
    superset_redis_data:
    superset_home:
    airflow-postgres_data: {}
    datalake: {}